#!/usr/bin/env python

#Plotting Output File

from numpy import *

import subprocess

import Gnuplot

#subprocess.call(['./Xyce','mscmemory_cell.cir'])

g = Gnuplot.Gnuplot()

g.plot(Gnuplot.File('spice.out', using=(2,3), with_= "lines"))

subprocess.call('gnuplot')

